name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Set up Python
      uses: actions/setup-python@v4  
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run tests
      run: |
        poetry run pytest --cov-config=.coveragerc --cov=src

    - name: Check PEP 8 compliance
      run: |
        poetry run black --check src

    - name: Lint with flake8
      run: |
        poetry run flake8 src

    - name: Trigger CD workflow
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/hugodegieter/demo-projet/actions/workflows/deploy.yml/dispatches \
        -d '{"ref":"master"}'