name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run tests
      run: |
        poetry run pytest --cov=src

    - name: Check PEP 8 compliance
      run: |
        poetry run black --check src

    - name: Check for type errors
      run: |
        poetry run mypy src

    - name: Lint with flake8
      run: |
        poetry run flake8 src