name: Deploy to Streamlit Cloud

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Deploy to Streamlit Cloud
      run: |
        curl -X POST https://api.streamlit.io/v1/deploy \
        -H "Content-Type: application/json" \
        -d '{"branch": "master", "repository": "hugodegieter/demo-projet"}'